# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SVNmain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Smain(object):
    def setupUi(self, Smain):
        Smain.setObjectName("Smain")
        Smain.resize(465, 259)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/HN.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Smain.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Smain)
        self.pushButton.setGeometry(QtCore.QRect(40, 80, 141, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Smain)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 80, 141, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Smain)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 10, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Smain)
        self.pushButton.clicked.connect(Smain.deploy)
        self.pushButton_2.clicked.connect(Smain.adduser)
        self.pushButton_3.clicked.connect(Smain.help)
        QtCore.QMetaObject.connectSlotsByName(Smain)

    def retranslateUi(self, Smain):
        _translate = QtCore.QCoreApplication.translate
        Smain.setWindowTitle(_translate("Smain", "svnauto v0.1"))
        self.pushButton.setText(_translate("Smain", "部署开发环境"))
        self.pushButton_2.setText(_translate("Smain", "添加用户"))
        self.pushButton_3.setText(_translate("Smain", "帮助"))


class Ui_Sdeploy(object):
    def setupUi(self, Sdeploy):
        Sdeploy.setObjectName("Sdeploy")
        Sdeploy.setEnabled(True)
        Sdeploy.resize(340, 381)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/HN.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sdeploy.setWindowIcon(icon)
        Sdeploy.setWindowOpacity(1.0)
        Sdeploy.setToolTipDuration(-1)
        Sdeploy.setAutoFillBackground(False)
        self.pushButton = QtWidgets.QPushButton(Sdeploy)
        self.pushButton.setGeometry(QtCore.QRect(250, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Sdeploy)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 220, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Sdeploy)
        self.lineEdit.setGeometry(QtCore.QRect(30, 20, 271, 31))
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Sdeploy)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 260, 281, 71))
        self.plainTextEdit.setWhatsThis("")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.checkBox = QtWidgets.QCheckBox(Sdeploy)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(30, 140, 71, 16))
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setToolTipDuration(0)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(Sdeploy)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 80, 131, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_2 = QtWidgets.QCheckBox(Sdeploy)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 170, 71, 16))
        self.checkBox_2.setAcceptDrops(False)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setAutoRepeat(False)
        self.checkBox_2.setAutoExclusive(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(Sdeploy)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QtCore.QRect(180, 170, 71, 16))
        self.checkBox_4.setAcceptDrops(False)
        self.checkBox_4.setAutoFillBackground(False)
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setAutoRepeat(False)
        self.checkBox_4.setAutoExclusive(False)
        self.checkBox_4.setObjectName("checkBox_4")

        self.retranslateUi(Sdeploy)
        self.pushButton.clicked.connect(Sdeploy.close)
        self.pushButton_2.clicked.connect(Sdeploy.send)
        QtCore.QMetaObject.connectSlotsByName(Sdeploy)

    def retranslateUi(self, Sdeploy):
        _translate = QtCore.QCoreApplication.translate
        Sdeploy.setWindowTitle(_translate("Sdeploy", "呆腻灰"))
        self.pushButton.setText(_translate("Sdeploy", "关闭"))
        self.pushButton_2.setText(_translate("Sdeploy", "发送部署"))
        self.lineEdit.setText(_translate("Sdeploy", "192.168.0.1"))
        self.lineEdit.setPlaceholderText(_translate("Sdeploy", "服务器IP"))
        self.plainTextEdit.setPlainText(_translate("Sdeploy", "状态..."))
        self.checkBox.setText(_translate("Sdeploy", "SVN"))
        self.lineEdit_2.setPlaceholderText(_translate("Sdeploy", "项目名"))
        self.checkBox_2.setText(_translate("Sdeploy", "samba"))
        self.checkBox_4.setText(_translate("Sdeploy", "Mysql"))

class Ui_Sadd(object):
    def setupUi(self, Sadd):
        Sadd.setObjectName("Sadd")
        Sadd.setEnabled(True)
        Sadd.resize(340, 381)
        Sadd.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/HN.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sadd.setWindowIcon(icon)
        self.lineEdit = QtWidgets.QLineEdit(Sadd)
        self.lineEdit.setGeometry(QtCore.QRect(40, 20, 271, 31))
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Sadd)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 80, 131, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Sadd)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 120, 131, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox = QtWidgets.QCheckBox(Sadd)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(40, 190, 71, 16))
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setToolTipDuration(0)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Sadd)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 190, 71, 16))
        self.checkBox_2.setAcceptDrops(False)
        self.checkBox_2.setToolTipDuration(0)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(Sadd)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 220, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Sadd)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 260, 281, 71))
        self.plainTextEdit.setWhatsThis("")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(Sadd)
        self.pushButton.setGeometry(QtCore.QRect(250, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Sadd)
        self.pushButton.clicked.connect(Sadd.close)
        self.pushButton_2.clicked.connect(Sadd.send)
        QtCore.QMetaObject.connectSlotsByName(Sadd)

    def retranslateUi(self, Sadd):
        _translate = QtCore.QCoreApplication.translate
        Sadd.setWindowTitle(_translate("Sadd", "逸起灰"))
        self.lineEdit.setText(_translate("Sadd", "192.168.0.1"))
        self.lineEdit.setPlaceholderText(_translate("Sadd", "服务器IP"))
        self.lineEdit_2.setPlaceholderText(_translate("Sadd", "项目名"))
        self.lineEdit_3.setPlaceholderText(_translate("Sadd", "用户名"))
        self.checkBox.setText(_translate("Sadd", "权限读写"))
        self.checkBox_2.setText(_translate("Sadd", "权限只读"))
        self.pushButton_2.setText(_translate("Sadd", "发送部署"))
        self.plainTextEdit.setPlainText(_translate("Sadd", "状态..."))
        self.plainTextEdit.setPlaceholderText(_translate("Sadd", "11111"))
        self.pushButton.setText(_translate("Sadd", "关闭"))

    def retranslateUi(self, Sadd):
        _translate = QtCore.QCoreApplication.translate
        Sadd.setWindowTitle(_translate("Sadd", "逸起灰"))
        self.lineEdit.setText(_translate("Sadd", "192.168.0.1"))
        self.lineEdit.setPlaceholderText(_translate("Sadd", "服务器IP"))
        self.lineEdit_2.setPlaceholderText(_translate("Sadd", "项目名"))
        self.lineEdit_3.setPlaceholderText(_translate("Sadd", "用户名"))
        self.checkBox.setText(_translate("Sadd", "权限读写"))
        self.checkBox_2.setText(_translate("Sadd", "权限只读"))
        self.pushButton_2.setText(_translate("Sadd", "发送部署"))
        self.plainTextEdit.setPlainText(_translate("Sadd", "状态..."))
        self.pushButton.setText(_translate("Sadd", "关闭"))

class Ui_explain(object):
    def setupUi(self, explain):
        explain.setObjectName("explain")
        explain.resize(232, 299)
        explain.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/HN.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        explain.setWindowIcon(icon)
        explain.setAutoFillBackground(True)
        self.widget = QtWidgets.QWidget(explain)
        self.widget.setGeometry(QtCore.QRect(0, 0, 231, 301))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 231, 241))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/HN.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 240, 221, 51))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(explain)
        QtCore.QMetaObject.connectSlotsByName(explain)

    def retranslateUi(self, explain):
        _translate = QtCore.QCoreApplication.translate
        explain.setWindowTitle(_translate("explain", "说米"))
        self.label_2.setText(_translate("explain", "<html><head/><body><p>摆烤鸭一只，可乐一瓶，</p><p>呐喊一声：汪悟理，召唤人形帮助文档</p></body></html>"))